# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=1.0.1
group=com.notjang.rosen
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Rosen
mod_author=Notjang
mod_id=rosen
license=MIT
credits=
description=Rosen is a lightweight mod that aims to expand on the noteblock system by adding more instruments, while trying to keep the sound design on the same level as the vanilla Minecraft.\n\nCurrently Rosen adds 18 new carefully crafted instruments such as Saxophone, Organ, Sitar, Music Box, Timpani and more! Rosen also features a Quality of Life addition that allows to play already existing instruments with the other blocks of a similar type.
homepage_url=https://modrinth.com/project/rosen
git_url=https://github.com/Biverom/rosen
update_url=https://raw.githubusercontent.com/Biverom/rosen/refs/heads/master/forge/update.json
minecraft_version_range=[1.21.1, 1.22)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21
parchment_version=2024.11.10

# Fabric
fabric_version=0.109.0+1.21.1
fabric_loader_version=0.16.9
modmenu_version=11.0.3

# Forge
forge_version=52.0.28
forge_loader_version_range=[52,)

# NeoForge
neoforge_version=21.1.80
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
